//
//  CommandService用のParam型とResult型を定義したprotoファイル
//

// ライセンスヘッダ:バージョン3を利用

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: command.proto

// パッケージの宣言

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 更新の種類
type CRUD int32

const (
	CRUD_UNKNOWN CRUD = 0 // 不明
	CRUD_INSERT  CRUD = 1 // 追加
	CRUD_UPDATE  CRUD = 2 // 変更
	CRUD_DELETE  CRUD = 3 // 削除
)

// Enum value maps for CRUD.
var (
	CRUD_name = map[int32]string{
		0: "UNKNOWN",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETE",
	}
	CRUD_value = map[string]int32{
		"UNKNOWN": 0,
		"INSERT":  1,
		"UPDATE":  2,
		"DELETE":  3,
	}
)

func (x CRUD) Enum() *CRUD {
	p := new(CRUD)
	*p = x
	return p
}

func (x CRUD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRUD) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (CRUD) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x CRUD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRUD.Descriptor instead.
func (CRUD) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

// *****************************************
// 商品カテゴリ更新用param型とResult型の定義
// *****************************************
//
//	商品カテゴリ更新Param型
type CategoryUpParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crud          CRUD                   `protobuf:"varint,1,opt,name=crud,proto3,enum=proto.CRUD" json:"crud,omitempty"` // 更新の種類
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                      // 商品カテゴリ番号
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                  // 商品カテゴリ名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryUpParam) Reset() {
	*x = CategoryUpParam{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryUpParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUpParam) ProtoMessage() {}

func (x *CategoryUpParam) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUpParam.ProtoReflect.Descriptor instead.
func (*CategoryUpParam) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryUpParam) GetCrud() CRUD {
	if x != nil {
		return x.Crud
	}
	return CRUD_UNKNOWN
}

func (x *CategoryUpParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryUpParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 商品更新Param型
type ProductUpParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crud          CRUD                   `protobuf:"varint,1,opt,name=crud,proto3,enum=proto.CRUD" json:"crud,omitempty"` // 更新の種類
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                      // 商品番号
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                  // 商品名
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`               // 単価
	CategoryId    string                 `protobuf:"bytes,5,opt,name=categoryId,proto3" json:"categoryId,omitempty"`      // 商品カテゴリ番号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpParam) Reset() {
	*x = ProductUpParam{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpParam) ProtoMessage() {}

func (x *ProductUpParam) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpParam.ProtoReflect.Descriptor instead.
func (*ProductUpParam) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *ProductUpParam) GetCrud() CRUD {
	if x != nil {
		return x.Crud
	}
	return CRUD_UNKNOWN
}

func (x *ProductUpParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductUpParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpParam) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpParam) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

// 商品カテゴリ更新Result型
type CategoryUpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`   // 更新結果
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`         // 更新エラー
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // タイムスタンプ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryUpResult) Reset() {
	*x = CategoryUpResult{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryUpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUpResult) ProtoMessage() {}

func (x *CategoryUpResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUpResult.ProtoReflect.Descriptor instead.
func (*CategoryUpResult) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryUpResult) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *CategoryUpResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CategoryUpResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 商品更新Result型
type ProductUpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`     // 更新結果
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`         // 更新エラー
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // タイムスタンプ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpResult) Reset() {
	*x = ProductUpResult{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpResult) ProtoMessage() {}

func (x *ProductUpResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpResult.ProtoReflect.Descriptor instead.
func (*ProductUpResult) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *ProductUpResult) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductUpResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ProductUpResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x05proto\x1a\verror.proto\x1a\fmodels.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x0fCategoryUpParam\x12\x1f\n" +
	"\x04crud\x18\x01 \x01(\x0e2\v.proto.CRUDR\x04crud\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x8b\x01\n" +
	"\x0eProductUpParam\x12\x1f\n" +
	"\x04crud\x18\x01 \x01(\x0e2\v.proto.CRUDR\x04crud\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x05 \x01(\tR\n" +
	"categoryId\"\x9d\x01\n" +
	"\x10CategoryUpResult\x12+\n" +
	"\bcategory\x18\x01 \x01(\v2\x0f.proto.CategoryR\bcategory\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.proto.ErrorR\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x99\x01\n" +
	"\x0fProductUpResult\x12(\n" +
	"\aproduct\x18\x01 \x01(\v2\x0e.proto.ProductR\aproduct\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.proto.ErrorR\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*7\n" +
	"\x04CRUD\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x032\xc2\x01\n" +
	"\x0fCategoryCommand\x129\n" +
	"\x06Create\x12\x16.proto.CategoryUpParam\x1a\x17.proto.CategoryUpResult\x129\n" +
	"\x06Update\x12\x16.proto.CategoryUpParam\x1a\x17.proto.CategoryUpResult\x129\n" +
	"\x06Delete\x12\x16.proto.CategoryUpParam\x1a\x17.proto.CategoryUpResult2\xbb\x01\n" +
	"\x0eProductCommand\x127\n" +
	"\x06Create\x12\x15.proto.ProductUpParam\x1a\x16.proto.ProductUpResult\x127\n" +
	"\x06Update\x12\x15.proto.ProductUpParam\x1a\x16.proto.ProductUpResult\x127\n" +
	"\x06Delete\x12\x15.proto.ProductUpParam\x1a\x16.proto.ProductUpResultB\x80\x01\n" +
	"\tcom.protoB\fCommandProtoP\x01Z1github.com/zakzackr/grpc-microservices-demo-pb/pb\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_command_proto_goTypes = []any{
	(CRUD)(0),                     // 0: proto.CRUD
	(*CategoryUpParam)(nil),       // 1: proto.CategoryUpParam
	(*ProductUpParam)(nil),        // 2: proto.ProductUpParam
	(*CategoryUpResult)(nil),      // 3: proto.CategoryUpResult
	(*ProductUpResult)(nil),       // 4: proto.ProductUpResult
	(*Category)(nil),              // 5: proto.Category
	(*Error)(nil),                 // 6: proto.Error
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*Product)(nil),               // 8: proto.Product
}
var file_command_proto_depIdxs = []int32{
	0,  // 0: proto.CategoryUpParam.crud:type_name -> proto.CRUD
	0,  // 1: proto.ProductUpParam.crud:type_name -> proto.CRUD
	5,  // 2: proto.CategoryUpResult.category:type_name -> proto.Category
	6,  // 3: proto.CategoryUpResult.error:type_name -> proto.Error
	7,  // 4: proto.CategoryUpResult.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: proto.ProductUpResult.product:type_name -> proto.Product
	6,  // 6: proto.ProductUpResult.error:type_name -> proto.Error
	7,  // 7: proto.ProductUpResult.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 8: proto.CategoryCommand.Create:input_type -> proto.CategoryUpParam
	1,  // 9: proto.CategoryCommand.Update:input_type -> proto.CategoryUpParam
	1,  // 10: proto.CategoryCommand.Delete:input_type -> proto.CategoryUpParam
	2,  // 11: proto.ProductCommand.Create:input_type -> proto.ProductUpParam
	2,  // 12: proto.ProductCommand.Update:input_type -> proto.ProductUpParam
	2,  // 13: proto.ProductCommand.Delete:input_type -> proto.ProductUpParam
	3,  // 14: proto.CategoryCommand.Create:output_type -> proto.CategoryUpResult
	3,  // 15: proto.CategoryCommand.Update:output_type -> proto.CategoryUpResult
	3,  // 16: proto.CategoryCommand.Delete:output_type -> proto.CategoryUpResult
	4,  // 17: proto.ProductCommand.Create:output_type -> proto.ProductUpResult
	4,  // 18: proto.ProductCommand.Update:output_type -> proto.ProductUpResult
	4,  // 19: proto.ProductCommand.Delete:output_type -> proto.ProductUpResult
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_error_proto_init()
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
